/**
 * normalize-shapes.ts
 *
 * Reads SVG files from src/shapes/svgs/, extracts the single <path d="...">,
 * normalizes coordinates into a 100x100 box, and writes the generated
 * TypeScript file at src/shapes/generated/paths.ts.
 *
 * Usage: npx tsx scripts/normalize-shapes.ts
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename, extname } from "node:path";
import svgpath from "svgpath";

const SVG_DIR = join(__dirname, "..", "src", "shapes", "svgs");
const OUT_FILE = join(__dirname, "..", "src", "shapes", "generated", "paths.ts");
const BOX = 100;

interface RawShape {
  id: string;
  d: string;
  viewBox: [number, number, number, number];
}

function parseSvg(filePath: string): RawShape {
  const content = readFileSync(filePath, "utf-8");
  const fileName = basename(filePath, extname(filePath));

  // Extract viewBox
  const vbMatch = content.match(/viewBox="([^"]+)"/);
  if (!vbMatch) {
    throw new Error(`${fileName}.svg: missing viewBox attribute`);
  }
  const viewBox = vbMatch[1].split(/[\s,]+/).map(Number) as [number, number, number, number];
  if (viewBox.length !== 4 || viewBox.some(isNaN)) {
    throw new Error(`${fileName}.svg: invalid viewBox "${vbMatch[1]}"`);
  }

  // Extract path d attributes
  const pathMatches = [...content.matchAll(/<path[^>]*\bd="([^"]+)"/g)];
  if (pathMatches.length === 0) {
    throw new Error(`${fileName}.svg: no <path> element found`);
  }
  if (pathMatches.length > 1) {
    throw new Error(`${fileName}.svg: multiple <path> elements found (${pathMatches.length}). Only single-path SVGs are supported.`);
  }

  return { id: fileName, d: pathMatches[0][1], viewBox };
}

function normalize(d: string, viewBox: [number, number, number, number]): { d: string; width: number; height: number } {
  const [minX, minY, w, h] = viewBox;

  // Uniform scale: fit the longest side to BOX, preserve aspect ratio
  const scale = BOX / Math.max(w, h);
  const scaledW = Math.round(w * scale * 100) / 100;
  const scaledH = Math.round(h * scale * 100) / 100;

  // Center in the BOX x BOX area
  const offsetX = (BOX - scaledW) / 2;
  const offsetY = (BOX - scaledH) / 2;

  const normalized = svgpath(d)
    .translate(-minX, -minY)
    .scale(scale)
    .translate(offsetX, offsetY)
    .round(2)
    .toString();

  return { d: normalized, width: scaledW, height: scaledH };
}

function main(): void {
  const files = readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg")).sort();

  if (files.length === 0) {
    console.error(`No .svg files found in ${SVG_DIR}`);
    process.exit(1);
  }

  console.log(`Processing ${files.length} SVG file(s)...`);

  // Parse and normalize all SVGs once
  const shapes = files.map((file) => {
    const raw = parseSvg(join(SVG_DIR, file));
    const norm = normalize(raw.d, raw.viewBox);
    console.log(`  ${raw.id}: viewBox=[${raw.viewBox}] -> ${norm.width}x${norm.height} in 100x100 box`);
    return { id: raw.id, ...norm };
  });

  // Write TypeScript
  const tsEntries = shapes.map(
    (s) => `  { id: "${s.id}", d: "${s.d}", width: ${s.width}, height: ${s.height} },`
  );

  const output = `// AUTO-GENERATED by scripts/normalize-shapes.ts — do not edit.
// Run \`npm run build:shapes\` to regenerate from src/shapes/svgs/.

export interface ShapePath {
  /** Shape identifier (derived from SVG filename). */
  id: string;
  /** Path data normalized and centered within a 100x100 bounding box. */
  d: string;
  /** Actual width of the path within the 100x100 box. */
  width: number;
  /** Actual height of the path within the 100x100 box. */
  height: number;
}

export const SHAPE_PATHS: ShapePath[] = [
${tsEntries.join("\n")}
];
`;

  mkdirSync(join(__dirname, "..", "src", "shapes", "generated"), { recursive: true });
  writeFileSync(OUT_FILE, output, "utf-8");
  console.log(`Written ${OUT_FILE}`);

  // Write JSON catalog for non-JS consumers (Rails, etc.)
  const JSON_FILE = join(__dirname, "..", "src", "shapes", "generated", "catalog.json");
  const catalog = shapes.map((s) => ({ id: s.id, d: s.d, viewBox: "0 0 100 100", width: s.width, height: s.height }));
  writeFileSync(JSON_FILE, JSON.stringify(catalog, null, 2) + "\n", "utf-8");
  console.log(`Written ${JSON_FILE}`);
}

main();
